### ISSUE TITLE
remove accel sensor specific code, replace with IMU accel data

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#12]
We are not going to have an independent accelerometer in the final cube board since the IMU provides this data.  The code for the accel needs to be ripped out and replaced with references to the relevant IMU data.

**Comment by rowr111** [comment]
ok, this should all be fixed now and the code is using the same struct as before accel_data with x,y,z - the numbers being reported are a little different - it's now reporting in g*1000.  milli-g? yeah.

**Comment by bunnie** [comment]
I'll pull off the legacy accelerometer on my board and test the code

**Comment by bunnie** [comment]
Removed the accelerometer, board boots fine. Closing issue.
