### ISSUE TITLE
During charge mode think about what it means to receive an OTA brightness command

### ISSUE THREAD

**Issue by bunnie** [rowr111/cubegarden#17]
During charging mode, brightness is reduced.

However, an OTA brightness command can override that. What should we do in that case?

**Comment by rowr111** [comment]
if we're overriding for the sake of safety (if for some case we need to charge at night?) it might be good but it also seems pretty unlikely that we'll be charging cubes in a place where safety would also be a concern. I'm open to either way.

**Comment by bunnie** [comment]
Implement the following policy:

If brightness change messages come in during charging, remember
them, and restore them only after the changing is done.

Can amend later if this is the wrong thing to do.
