### ISSUE TITLE
dB effect should not use "shift" to set brightness

### ISSUE THREAD

**Issue by bunnie** [rowr111/cubegarden#21]
The "shift" parameter is reserved exclusively for globally dimming effects during e.g. charging.

The use of the "shift" parameter and variable in the dB effect means it doesn't respect dimming options correctly, so when this effect is set charging can't complete as-writ.

The main reason "shift" is even revealed was because for the "strobe" effect I wanted it to be bright even if "shift" is selected low, and it's a temporary effect so it doesn't affect charging. Maybe the API should have been written better...

**Comment by rowr111** [comment]
fixed by commit 2e0e09e.  also db bkgd and max thresholds are now tunable.
