### ISSUE TITLE
create backup raspberry pi image

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#24]
Have a raspberry pi prepared with an image that has the latest production-ready code on it as well as the cable needed to connect it to a heart badge.

**Comment by bunnie** [comment]
I think we'll have this covered -- i'm bringing two pi's, presumably you might be too?

The main thing is -- just make sure the tester is updated with the latest code, that's the one that matters...

**Comment by rowr111** [comment]
I'll bring mine, and we can bring one of Sara's, and the tester.  That should be plenty.

**Comment by bunnie** [comment]
Closing as this resolves the issue.
