### ISSUE TITLE
be able to simulate page from a phage badge from the command line (for testing)

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#3]
Since most people only have one badge, unless they have friends nearby it is hard to do development work related to being paged from a badge.  A command line ability to simulate a page would be useful for testing purposes.

**Comment by bunnie** [comment]
Feature added in commit c0444743c39dc4c45447cd550885850567577f0f

Please close if it works for you!

**Comment by rowr111** [comment]
It works!  thank you!
