### ISSUE TITLE
figure out method to protect battery from puncture by board

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#40]
the board has some pokey bits that stick out on the bottom - we do not want to puncture the battery, so we're thinking about putting something in between the two as a cushion.

**Comment by bunnie** [comment]
Now that we're integrating boards, is this a problem? I think the pokey bits are largely removed and we're safe.

**Comment by rowr111** [comment]
I think it'll be ok.. I brought some neoprene sheets from Japan with me that we can cut up and use if it seems like there will be a problem during assembly, but so far it looks ok to me.
