### ISSUE TITLE
watchdog seems like it might be a little too aggressive

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#41]
I've had boards restart on me once or twice when nothing was wrong and they weren't frozen and everything was working fine.  If the watchdog is too aggressive this will get annoying in production.

**Comment by bunnie** [comment]
New submodule commit: 5775e8ef41d83258974cff5f2a09b1d48c48596d

fixes this. need to pull and do 'git submodule update' to grab it.
