### ISSUE TITLE
make 'no fun mode' stealing deterrent able to be turned off

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#48]
If you want to enable a few cubes to be taken away for independent play, but generally have them on stealing deterrent mode enabled, you could make this configurable via a new saved config value and settable via the master badge.

**Comment by bunnie** [comment]
This is now pre-playa essential so the cubes have utility after the burn at the place where they will be stored.

**Comment by bunnie** [comment]
This has been integrated, now in testing.

**Comment by rowr111** [comment]
can confirm that turning 'no fun mode'off works.  some effects won't be too useful without a master badge but the cubes will work now.
