### ISSUE TITLE
finalize theft deterrent parameters

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#50]
currently set to 3min waiting on the ping but might want to make it shorter (like 1.5min and ping more often).. need to finalize this.

**Comment by bunnie** [comment]
I've added a setting to adjust the interval between time sync broadcasts, so this gives some flexibility on the interval for no fun mode.

**Comment by rowr111** [comment]
ok - we can leave TIME_PING_MAX_WAIT to 18000, and I think between that and setting the ping interval we should be ok.  I'm fine with this.  If it ends up just being horrible at least we can turn it off now if needed.
