### ISSUE TITLE
LOTC - finalize 'flash' signaling length and number of repeats

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#51]
figure out how many flashes and how long the flashes should be to properly signal when the baton has been passed.  current settings seem to be a bit too quick.

**Comment by bunnie** [comment]
I've modified the LOTC effect to use the radio-configurable parameter cfg_fx_newcube_time so this is a thing you can tune on-playa. If you don't like how I did it go ahead and re-open this. I was careful to make sure the commits are separate from the rest of the refactor so you can just cherry-pick the commits out without breaking the git history.
