### ISSUE TITLE
add retransmit to master badge key functions

### ISSUE THREAD

**Issue by bunnie** [rowr111/cubegarden#58]
in particular around brightness setting, but also it seems somehow fx selection is missing that.

I thought I had added this before, but I just checked, it's missing.

This only affects the master-badge.

**Comment by rowr111** [comment]
FWIW, fx selection seems to send multiple times anyway, unless you're the type of person who only quickly taps the A button.

**Comment by bunnie** [comment]
I've checked and covered all the relevant radio paths with retransmits, so that setting effects and brightness should be a little less frustrating.
