### ISSUE TITLE
cubes don't always charge

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#65]
not sure if this is a dust problem or a problem with the charging port.  needs investigation bc we had a lot of cubes have this problem.

**Comment by bunnie** [comment]
I think we've made our best attempt to resolve this with the cube telemetry to be able to get feedback on when the cube is not charging. Until we get more data, we can't solve the problem, so I'll close this and we can open a new bug if we find a new endemic problem based on the telemetry.
