### ISSUE TITLE
add dB effect as an optional overlay on effects instead of its own effect

### ISSUE THREAD

**Issue by rowr111** [rowr111/cubegarden#67]
Basically this effect was so popular that it seems integral to the cubegarden experience.  We should just add it on top of effects.

**Comment by boberj** [comment]
I want to simplify effects development by creating a way to more abstractly describe effects (color change, pulsing etc.) and then layer/blend them together to create a complete new effect. Seems like that could be used to implement this by treating a complete effect as just another layer.

**Comment by rowr111** [comment]
yeah.. my general idea is along those lines - the base effect would reduced to be color palettes only.  you'd pick the color palette you'd like, and then build your effect by picking all the other 'moving' parts - pulsing, db effect, tilting, change color on tap, etc.

**Comment by rowr111** [comment]
this effect is in and looking pretty good (imho, lol) as of commit 4d1a8d0
